# This is a basic workflow to help you get started with Actions

name: DeployTest

# Controls when the workflow will run
on:
  
  push:
    branches: [ "main" ]
    



jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: DeployTest
        run: |
          echo "Hello"
